# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: DuanYuchen
google_analytics: DuanYuchen
title: Stee1Forest

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Test

description: Stylish Jekyll Theme
author:
  name: DuanYuchen
  email: 1184401036@qq.com
  github: Stee1Forest
  twitter: 
  pinterest: 
  linkedin: 
  bio: Forever rookie
  email_md5: 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
